### ISSUE TITLE
Change favorite language from PHP

### ISSUE THREAD

**Issue by dvtate** [dvtate/old.dvtt.net#1]
PHP IS SOOOOOOOO LAME
C is waaaaay better :smiley:

**Comment by dharnarh** [comment]
Can you use c on a website. I don't think I had of it.

**Comment by dvtate** [comment]
@humarh-dharnarh this is for a section of my homepage. I haven't changed it in several years and PHP isn't really all that great. Only thing I need is a good Logo for C/C++
![image](https://user-images.githubusercontent.com/15305612/27257591-406a8444-53aa-11e7-827d-4a14cfd03d64.png)
![image](https://user-images.githubusercontent.com/15305612/27257594-4aceb70c-53aa-11e7-8ea4-907207480b68.png)

**Comment by dvtate** [comment]
I might replace it with a link to [https://github.com/dvtate/yoda](url)

**Comment by dharnarh** [comment]
Okay
